"""Refresh the trading universe from the current S&P 500 constituents.

Writes tickers to config/universe.txt (gitignored, machine-generated), one per line.
The trading pipeline reads that file, so it never scrapes at trade time. Run on a slow
cadence (weekly); S&P 500 membership changes only a few times a year.

Any failure keeps the existing universe rather than wiping it, so a bad fetch degrades
to "no change" instead of an empty universe.

Usage: python scripts/refresh_universe.py
"""

import io
import sys
from pathlib import Path

import pandas as pd
import requests

from diyquant.config import PROJECT_ROOT

WIKI_URL = "https://en.wikipedia.org/wiki/List_of_S%26P_500_companies"
OUT_PATH = PROJECT_ROOT / "config" / "universe.txt"
MIN_EXPECTED = 400  # a healthy fetch is ~500; far fewer means a bad parse, so refuse it


def fetch_sp500() -> list[str]:
    html = requests.get(WIKI_URL, headers={"User-Agent": "Mozilla/5.0"}, timeout=30).text
    tables = pd.read_html(io.StringIO(html))
    symbols = tables[0]["Symbol"].astype(str).str.strip().tolist()
    # yfinance uses '-' for share classes: BRK.B -> BRK-B
    symbols = [s.replace(".", "-") for s in symbols if s and s.lower() != "nan"]
    return sorted(set(symbols))


def read_existing(path: Path) -> list[str]:
    if not path.exists():
        return []
    return [
        line.strip()
        for line in path.read_text(encoding="utf-8").splitlines()
        if line.strip() and not line.strip().startswith("#")
    ]


def main() -> None:
    try:
        tickers = fetch_sp500()
    except Exception as e:  # noqa: BLE001 - any failure must not wipe the universe
        existing = read_existing(OUT_PATH)
        if existing:
            print(
                f"fetch failed ({e}); keeping existing {len(existing)} tickers",
                file=sys.stderr,
            )
            sys.exit(1)
        print(f"fetch failed ({e}) and no existing universe to fall back on", file=sys.stderr)
        raise

    if len(tickers) < MIN_EXPECTED:
        existing = read_existing(OUT_PATH)
        print(
            f"fetch returned only {len(tickers)} tickers (< {MIN_EXPECTED}); refusing to "
            f"overwrite. keeping {len(existing)} existing.",
            file=sys.stderr,
        )
        sys.exit(1)

    previous = set(read_existing(OUT_PATH))
    current = set(tickers)
    added = sorted(current - previous)
    removed = sorted(previous - current)

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    header = (
        "# Machine-generated by scripts/refresh_universe.py. Do not edit by hand.\n"
        "# Current S&P 500 constituents, one ticker per line.\n"
    )
    OUT_PATH.write_text(header + "\n".join(tickers) + "\n", encoding="utf-8")

    print(f"universe: {len(tickers)} tickers -> {OUT_PATH}")
    if previous:
        print(f"added ({len(added)}): {added}")
        print(f"removed ({len(removed)}): {removed}")
    else:
        print("seeded universe for the first time")


if __name__ == "__main__":
    main()
